apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wallabag-values
  namespace: wallabag
spec:
  encryptedData:
    values.yaml: AgDihEejhMm8WQSoRCZdzxg1IejWW8qArqmeMqVig4PGxL2WTHr8HEXY7rXS+cUuYniTK+uWfCGham8SS8kFCMJbPPeA0Cz/DB9AgqIBzHt3XgAlmXm3FA51YOxa5vThndca9gAR11j0yRrzVIs1FIpSt6SKu0zfq0osLfu9/9FsvqsDJDM6zbBdI9VgJSXvCEaAXNm4nLAqxzjM1n6E27qjLEZHZ8oxtNlGr9djWL8AYlLPBd2Nj62e6AL0XTwCz2XoPnfGx7BylGHsI1Ogkq8Ysy/hBkexMf7pB/8YR89J+zyfpbNjWDwYpINUVLBaT2uNHs3TSDJpnMjojn68ULxHFxALPsNieJxaW0sdkyOpvYlPpWhV5u29p/OQ2iu6aszXfoKJQXDz7pG5y+ppaFop7xN8GIbC2snN4LmH29dLR7DhaT3n2e5hogWOyDzdmYJcKc26gSRynCcycLQhJn/hRuCNPm67wEiuVfHJtWbBq4cnXVMJ42TnqAuBdCp5mQWIDP6o8vdGYJD/evBaw2CinGnbc1UGRXd2MxMXnaiFliKs1ZneV6/tekWUEl0tcnJI020yJ387WJ4s4Ruu2sCBKH0p1HCTHPA10zoGHRLLYky2TJucfhS3V2tXQyzwigbKoPORpaGwyHRqonhGOxy0u98CiwpVj5X5/4fL2ZfsPbUAHG4lp7LmceFAVzuUtd7K7XcaqSjg2DKXe8AEay4Me4X8HqSXGzxpM+vKKksI3tWi+BsnN9VaE5zT4nXrlPFwyVQpX0GOq6OzdmGENJTIgfNQvt/SMspYBjoXw8aNI7hjsMm0TcE7pGY3O5Sl4jY1HrTbtljs0j8IlVC9+2am4ZPyWUqYGRsUH/GItbPEzIYRm2QzNchi61QT
