apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwardenrs
spec:
  interval: 1h
  chart:
    spec:
      chart: bitwardenrs
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: bitwardenrs/server
      tag: 1.17.0
    bitwardenrs:
      domain: warden.zro.io
    persistence:
      existingClaim: bitwarden-database
    ingress:
      enabled: true
      hosts:
      - host: warden.zro.io
        paths: [ "/" ]
