---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vernemq-data
  namespace: home-assistant
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 4Gi

  storageClassName: rook-ceph-block
