apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-values
  namespace: media
spec:
  encryptedData:
    values.yaml: AgB+uY+mEaz91kiN8MsK1TmPv3AG6ysCGH5MH8TV85hjs+Rr6bsXLaVtBUv+cr4jU4+ubXNYBU7YJAae7cIKKHaKYpZWGWDFQ65x2NQOJRw839nlTLPAObGJhzLadk7h66t7gPieNih4B1wE5c1RXySZJG73lMSfpQijJN+WXm2WP2WAbHLPNZpNS02lzVxNNRSLL8zKdKg1Q0esE1BzYxCaMSlfTIuzrHGldBqZo5R0Vf6sMFKVvkcR/skqznjFFIyqoKzwqYjhzNOFBpfC1fLRf5nlCNd/wMGYZBToT/Xz1gBaXRQ+ditbxWGjhWV4QeEDvbsGAuxZC8DuLpQlDKxF+DLRBVoqbgb+DYpt4uKv7umkugZqzH/pWaYE4+l+R92Z2bTyrJrONAL7ik7eSusHj2e8NoewLhbfryJ5vh5BcaoTOf0OS5qthT6B01Fjo8WJINQby3cVxffczqISsm160wLdVRWutUq57oX+hXiqhQvbxwkYODzCDKfWSzFiPQ4rwTd2ZzUdyC7bsBe60bcIXaunVlkt/vhhx9UMUSJZQhreEBUGIpJADYx7vIW0BD8adUcYWCHvYX+2EtbBJ22SlkYtrW3GwPaTaSUZajqAiQczPzjhR8p1Koi9A7EsHWEu+H4tnXI2tnYtCsIckt6booF3oEpESdGf3ljS076ShhDiVixMsadvDN4UcZvsMeos3PK5DRvrOjXhRW66c929GusctRKMjVevVH9jPyW1+BJHWrKG+TM=
