apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-values
  namespace: home-assistant
spec:
  encryptedData:
    values.yaml: AgAFivDT8BpSvux4G5dqTLRem4JmVLrtlYF/P5prqsjTGdVxvQY33Hf1XUvZwklf07f2chSZWhePEKqRKaw0hRl+7lPEW9IWtA+zSg4F3VEu3jvtrz65xTfM+rgKHnSzY7UbCd2hrZZbTaBKGWoInvLB3A8X/4ElbnT3apua2ZQlT+6dtW0ynT43G3aspAQ3x4mTJkaOK66j4BQe0Q5bwpmijpuNEJE3HIpVDa6NnxtHZ2+i2LSUV0WynYxQGRrvdlFWZKC9Bxz9oz+sIOKRPNZ7EliSYp/RxqyIRiobTwErDZaQhc+FZe3rPxj4+WvlrQ+e3ChV2m+R+1D7nKJSEXqic9zBHjp/aDfv/913dOFOb4m+H6aapkvJatAx9hivzLS/y3RUykw/OV5nBtRGjlmwYqv4DA6B48Mi0nmwF5w46gD2YsAeEkrJnwi8GCblgI25BOnSzq69+iXaiSJeJuddmCo9T2bmF0wgPYiXXP3QuKq2qBakelB4iUgaIowaB7QDj33Nkhwk2eVGhJtboJbbuAiATG2vexNjQc1OzwISFixYeHVN6ul6Liw0Xg9qgDOQM3LMrs8BbdOLkX6EI2FTNqdRwlXEiIqda5ZVxUkLvmJCS4oUWWmhI+lk5cvvutUy+YGc9urYUfxq14iZAzc5iOv2CmtX9dZXa5w1U+SwqgKrOlF3/PnZ9kq3MU0RDW9tHxpfOfLemoVxRPP+WrkU4USscEUzuqh6RanxTW/W7bYpZpyirq9FUS2WuwahoCInXE7hSSAVNY/I9+tacAgmOGIBtNcM
