apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zwave
  namespace: home-assistant
spec:
  encryptedData:
    networkKey: AgCsJXA2J9GkFfjN/r6Yrj7+xsPFDcfe3WDaDvG8TP0SefoOd+XFngHRrNPdLXb+vTZk5sW+9hyg8BZwjbmbBEVtuEVihWUcVph7CArD2k+H7hntaHROwkpW5oG9RwrYzeTOL1X1LYnes+tB0KG2RLHWgXTYP1TIGAxR/Eix/ytRgTGVzZk+/8+nGuBFhiyq6Q1c++jwEsq1fDdT5rKogwoiV8p2y71XLhERoK7OPZOhb3uM7TIRN0zXlI4WGphXrUcUkOigX7fatwXa+l8nP2GcGY7gfKVih0ZdPYxgcICa9DsenRizSMfo2gpG9R+CnDzwp1OlGCHFLNpY+BxyQ5EyPwgfLR8ZNfIbTHh5I3fOw6VpKO1mkfIZ7FPLH1ViqEXbD+kLWTM5VDIha7NL323MNC+udeTLIY5jbkcLqkr76zIkOfKaJciRFDoJogsvm5IuEyH35ndhpRouIN6Df6RRWdi5FGNOolX/5r9n1vF9L+UoZTpZfKO79JqZq8/W7sktO19mVPtTUPBYtwuopWoL6rdBzZJ6G1iso6+tVikmaUGyC37AGxA2C6xe9Ilcgm2Aqq/Va6pcZaYhuUbZiyNQBZXxcQLLJbhBV+FjCbCo9iO4dxeKUGP2hzKcI9B4z5HLIUjY1TXiw49v/p87WJITvPKoNOCWDuBA1Ya0/qG7NaD1VUNQFHJpldrUSU68pp4EyQ4s2Uw6aCArbaeHTisTHVkUkvvNNWHCPoZSu72YGpR502xkU3i+/zPFmaTKztW/vJtWyHu2uJApVuod3PeZtDQhA4UIPwmQDQXlYgfe7vVw4Zmsamy/sWJAp4LJ
