apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zwave
  namespace: home-assistant
spec:
  encryptedData:
    networkKey: AgBNfEhF5xA+TrKBB/Rw2JRy5HIuH8hZPMS1zd3BGkRHbDIoYH2bBkuujLVoKBvbCyHq2iubD6/SI4PWgg5uXeb1u8uRupyqXZazB5jou+ZHH+gZmkBBTZsAAAPgX5VJDbkGERVONA/yESJWaIR0ptxggNuuIxPlJuJxRw7phUcHcr1mD/gmYBVaSv/jWgJ6GvHb+Zoo0c/JjAzCn3aISKLZfhlyJbXWgU01ZOD6Abw9XUn6DOHiODAJOy+M7PS1gVNQOYzxfmj5M+3K4ANVDvsazi12iKEFOWJ1/B/5D+EtIOt5VL3pZDUCDUolENvJWd2yNQUVMkXnXlcNoEBJi/Qrc6XwV2iI5c9nl2U19yliH+VRHLP7l0DJ2gH5ljEvm7jtti97nn2fxiSoxd6ixP62ic4oGFJ0P+4vRz30Xxc72xQpG3y9ecXEfnekowLLfS/1iEhZrGXQmGpfnb8/z2fi45lQJf8YCnaxaxymz9nepsZdNWsa4e8piqltRdBPiXx7x9VLSSv5c6lpub4snAb7beZyP00M//b6ElXMVgFkF6ICEijNA2q9h5vdGDm7WLd7/7Bx7sQuOEt5bJRvucPbnXzIQ0rmGFt2bbb3eS+f+nYe0AB3rB5G/lZ02HE4fjIj3Ym50l91ollMdYszo3hwxDKNyCD4B79Koehj56uT2hnEs3knlri7PECENhoT61fIjGEipvMuNpvqheQMR+KZ9gv9g55dP9uoCTtWQHcf3S0JNyQYSFcaU3MSehdfMkyYQYih//PfqQKH9+i6a7fzKI7MsQnPDNdtDXJWDWlvl1lJmC+4PJCzp/FBGDfD
