apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zwave
  namespace: home-assistant
spec:
  encryptedData:
    networkKey: AgCLyGl1ws47PmGnPx++dIE7Wl2FD29dMJqCLw66PKC6Cd356dvv0JsIlkebwXLaBb5sEHGq/Uie1rE8gtWjeazOXCQFYpL3+rpKK1S1EeI5ycpSi68OFKT3P6U3yq5cDyc3lRoYMbgRlfermo6DlrnbT86do2bJITJt+Xc1NEJba7HULY5eGSolnGjGf38/dgDeK+8eZUbBMIemf/CVybvBY/fJ6DDWSZBTZOnikGPqPy2myFSCPmNNqzEH7SGdnk7Ad//YHO0TpHSOCzgOD8sM5sBiExsIXMsSw0qkfxB2qWtcy7HrJB2m2/GOuKjoYI6b67hysTIL3FQiEzGkQVoPR1hXkQgWGGkB0508ctwBxFBhKw9f13M0ok5MjqUWatXT6W+GLjdUGZ+6JMaaE6pkjTU6XSZwuAK5WhaDLwvSkYhAHIWus7TrC5+0F6AihVtb4xPDumGmWdoF3fK8MIVMm4nq+WihVDidkvVd9dM39dDwm8ZV+ANfDiYvwgOOEejs9nHfP1rherYKTbXMNnK4lX5/6/yd1JWeooim9qNTsp/8FvzVFsATgk+FyS4ZPbtoVrkQ/C+4C6q50q6mBKXlTN4rQeAFSY3VgF9DrzsfjvldhSFPbAb2QDeonQYesbnZ9d7ZG9kzglxCBWwkaSKTvCidGMppCFNRhX/75wa9Vi8jNRLKctZgPsA2gV27zUhVAui5spwO5if0R5OP7a5RqwfgDmo0f8czDDXqgHVmEuLqjEUy/vi5RVCDGjsEzLuVZ/tCioJdsmFK55tQPxCEiwz7ylpFtyw0i362kwrBqJlMVOS+pJ+QASqZ0wsv
