apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stack
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 12.10.4
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    fullnameOverride: stack
    grafana:
      plugins:
      - grafana-piechart-panel
      # persistence:
      #   enabled: true
      #   size: 2Gi
      dashboards:
      env:
        # auth proxy settings
        GF_USERS_ALLOW_SIGN_UP: false
        GF_USERS_AUTO_ASSIGN_ORG: true
        GF_USERS_AUTO_ASSIGN_ORG_ROLE: Editor
        GF_AUTH_PROXY_ENABLED: true
        GF_AUTH_PROXY_HEADER_NAME: X-Forwarded-Email
        GF_AUTH_PROXY_HEADER_PROPERTY: email
        GF_AUTH_PROXY_AUTO_SIGN_UP: true
        # other settings
        GF_PANELS_DISABLE_SANITIZE_HTML: true
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-signin: https://auth.zro.io/oauth2/sign_in
          nginx.ingress.kubernetes.io/auth-url: https://auth.zro.io/oauth2/auth
        hosts:
        - grafana.zro.io
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
