apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stack
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 12.10.4
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    fullnameOverride: stack
    grafana:
      image:
        repository: grafana/grafana
        tag: 7.3.6
      plugins:
      - grafana-piechart-panel
      env:
        GF_PANELS_DISABLE_SANITIZE_HTML: true
      sidecar:
        datasources:
          enabled: true
        dashboards:
          enabled: true
          searchNamespace: ALL
      ingress:
        enabled: true
        hosts:
        - grafana.zro.io
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi

  valuesFrom:
  - kind: Secret
    name: prometheus-stack-values
