---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
  namespace: unifi
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 8Gi

  storageClassName: rook-ceph-block
