rtspPassword: {{ .FRIGATE_RTSP_PASSWORD }}

config: |
  web_port: 5000
  mqtt:
    host: vernemq.home-assistant
    user: {{ .FRIGATE_MQTT_USERNAME }}
    password: {{ .FRIGATE_MQTT_PASSWORD }}
  cameras:
    front:
      input: rtsp://frigate:{{ .CAMERA_410_1_PASSWORD }}@{{ .CAMERA_410_1_ADDRESS }}//h264Preview_01_sub
      height: 480
      width: 640
      fps: 7
