apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.6.1
    timezone: 'America/Chicago'
    ingress:
      enabled: true
      hosts:
      - frigate.zro.io
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.zro.io/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.zro.io/oauth2/start"
