apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/oauth2-proxy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      tag: v6.1.1
    replicaCount: 2
    ingress:
      enabled: true
      path: /
      hosts:
      - auth.zro.io
    extraArgs:
      provider: "github"
      provider-display-name: "Gitea"
      email-domain: "*"
      cookie-domain: ".zro.io"
      whitelist-domain: ".zro.io"
      login-url: "https://git.zro.io/login/oauth/authorize"
      redeem-url: "https://git.zro.io/login/oauth/access_token"
      validate-url: "https://git.zro.io/api/v1"
  valuesFrom:
  - kind: Secret
    name: credentials
    valuesKey: jwtSecret
    targetPath: config.cookieSecret
  - kind: Secret
    name: credentials
    valuesKey: clientId
    targetPath: config.clientID
  - kind: Secret
    name: credentials
    valuesKey: clientSecret
    targetPath: config.clientSecret
