apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 1h
  chart:
    spec:
      chart: oauth2-proxy
      version: 3.2.5
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
  values:
    image:
      tag: v6.1.1
    configFile: |-
      provider = "github"
      email_domain = "*"
    ingress:
      enabled: true
  valuesFrom:
  - kind: Secret
    name: credentials
    valuesKey: jwtSecret
    targetPath: config.cookieSecret
  - kind: Secret
    name: credentials
    valuesKey: clientId
    targetPath: config.clientID
  - kind: Secret
    name: credentials
    valuesKey: clientSecret
    targetPath: config.clientSecret
