nextcloud:
  host: cloud.zro.io
  username: {{ .USER_NAME }}
  password: {{ .NEXTCLOUD_ADMIN_PASSWORD }}
  defaultConfigs:
    autoconfig.php: false
    redis.config.php: false
  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array(
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://cloud.zro.io',
        'filelocking.enabled' => 'true',
        'loglevel' => 2
      );
    redis.config.php: |-
      <?php
      $CONFIG = array(
        'memcache.local' => '\\OC\\Memcache\\Redis',
        'memcache.distributed' => '\OC\Memcache\Redis',
        'memcache.locking' => '\OC\Memcache\Redis',
        'redis' => array(
          'host' => 'redis',
          'port' => 6379
        )
      );
    s3.config.php: |-
      <?php
      $CONFIG = aray(
        'objectstorage' => array(
          'class' => '\\OC\\Files\\ObjectStore\\S3',
          'arguments' = array(
            'bucket' => 'nextcloud',
            'autocreate' => true,
            'key' => '{{ .MINIO_INTERNAL_ACCESS_KEY }}',
            'secret' => '{{ .MINIO_INTERNAL_SECRET_KEY }}',
            'region' => 'us-east-1',
            'hostname' => '{{ .MINIO_INTERNAL_HOSTNAME }}',
            'use_ssl' => false,
            'use_path_style' => true
           );
        )
      );
internalDatabase:
  enabled: false
externalDatabase:
  type: postgresql
  host: postgres
  database: postgres
  existingSecret:
    enabled: true
    secretName: postgres-auth
    usernameKey: username
    passwordKey: password
