---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: ExternalName
  externalName: sonarqube-sonarqube.sonarqube.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: ExternalName
  externalName: harbor-harbor-core.registry.svc.cluster.local
