apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: sealed-secrets
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
  values:
    serviceMonitor:
      create: true
      interval: 60s
      scrapeTimeout: 30s
    dashboards:
      create: true
