apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 2
    csi:
      kubeletRootDir: /var/lib/kubelet
    defaultSettings:
      backupTarget: s3://longhorn-backups@us-west-000
      backupTargetCredentialSecret: backup-credentials
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      host: longhorn.inwin-cluster.zro.io
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.zro.io/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.zro.io/oauth2/start"
