apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: 3.10.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 2
      extraArgs:
        default-ssl-certificate: "ingress-system/zro-wildcard-certificate"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
