apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: organizr
spec:
  interval: 1h
  chart:
    spec:
      # renovate not setup here since organizr only publishes :latest
      chart: organizr
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: organizr/organizr
      tag: latest
      pullPolicy: Always
    strategy:
      type: Recreate
    env:
      TZ: America/Chicago
    persistence:
      config:
        enabled: true
        existingClaim: organizr-config
    ingress:
      enabled: true
      hosts:
      - host: organizr.zro.io
        paths:
        - path: /
          pathType: Prefix
