apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: redis
spec:
  version: 6.0.6
  mode: Standalone
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  podTemplate:
    spec:
      resources:
        requests:
          memory: 64Mi
