apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blocky
resources:
- namespace.yaml
- release.yaml

configMapGenerator:
- name: dashboard
  files:
  - dashboard.json
  options:
    labels:
      grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
