apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-pool
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-nfs
  resources:
    requests:
      storage: 6Ti
