apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 1h
  chart:
    spec:
      chart: minio
      version: 8.0.3
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    image:
      tag: RELEASE.2020-11-19T23-48-16Z
    mode: standalone
    DeploymentUpdate:
      type: Recreate
    existingSecret: credentials
    ingress:
      enabled: true
      hosts:
      - s3.zro.io
    metrics:
      serviceMonitor:
        enabled: true
