apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://helm.min.io/
      chart: minio
      version: 8.0.9
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    image:
      repository: minio/minio
      tag: RELEASE.2020-12-03T05-49-24Z
    mode: standalone
    DeploymentUpdate:
      type: Recreate
    existingSecret: credentials
    ingress:
      enabled: true
      hosts:
      - s3.zro.io
    metrics:
      serviceMonitor:
        enabled: true
    persistence:
      enabled: true
      existingClaim: minio-external
