apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
spec:
  interval: 1h
  chart:
    spec:
      chart: sonarqube
      version: 9.1.2
      sourceRef:
        kind: HelmRepository
        name: oteemo
        namespace: flux-system
  values:
    image:
      tag: 8.5.1-community
    ingress:
      enabled: true
      hosts:
      - name: sonarqube.zro.io
        path: /
    initContainersSecurityContext:
      privileged: false
    persistence:
      enabled: true
    postgresql:
      enabled: false
      postgresqlServer: postgres.sonarqube.svc
      postgresqlDatabase: postgres
      postgresqlUsername: postgres
  valuesFrom:
  - kind: Secret
    name: postgres-auth
    valuesKey: password
    targetPath: postgresql.postgresqlPassword
