apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.118.5
    extraEnv:
      TZ: America/Chicago
    extraSecretForEnvFrom:
    - home-assistant-env
    hostNetwork: true
    ingress:
      enabled: true
      hosts:
      - host: home-assistant.zro.io
        paths:
        - path: /
          pathType: Prefix
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
    persistence:
      config:
        enabled: true
        size: 4Gi

    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/auth-signin: https://auth.zro.io/oauth2/start
            nginx.ingress.kubernetes.io/auth-url: https://auth.zro.io/oauth2/auth
            nginx.ingress.kubernetes.io/proxy-body-size: 0
          hosts:
          - host: home-vscode.zro.io
            paths:
            - path: /
              pathType: Prefix
        workingDir: /config
        volumeMounts:
        - name: config
          mountPath: /config
        - name: deploykey
          mountPath: /root/.ssh/id_ed25519
          subPath: id_ed25519
