apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.118.5
    extraEnv:
      TZ: America/Chicago
    extraSecretForEnvFrom:
    - home-assistant-env
    ingress:
      enabled: true
      hosts:
      - home-assistant.zro.io
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
    git:
      enabled: true
      repo: https://github.com/zacheryph/hass-config
      secret: github-credentials
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.7.4
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-signin: https://auth.zro.io/oauth2/start
          nginx.ingress.kubernetes.io/auth-url: https://auth.zro.io/oauth2/auth
        hosts:
        - home-vscode.zro.io
