apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name:
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: zwave2mqtt
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: robertslando/zwave2mqtt
      tag: 4.1.1
    env:
      TZ: "America/Chicago"
      OZW_AUTO_UPDATE_CONFIG: true
    persistence:
      config:
        enabled: true
        size: 1Gi
    additionalVolumeMounts:
    - name: usb
      mountPath: /dev/serial/by-id/usb-0658_0200-if00
    additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/serial/by-id/usb-0658_0200-if00
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "feature.node.kubernetes.io/custom-zwave"
              operator: In
              values: [ "true" ]
