apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.21.0.3711-b509cc236
    timezone: "America/Chicago"
    allowedNetworks:
    - 127.0.0.1
    - 10.42.0.0/16
    - 10.72.143.0/24
    persistence:
      data:
        claimName: media-pool
    ingress:
      enabled: true
      hosts:
      - plex.zro.io
    serviceTCP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
    serviceUDP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: plex-svc
    resources:
      requests:
        cpu: 2000m
        memory: 4000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 12000Mi
  valuesFrom:
  - kind: Secret
    name: plex-values
