apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  chart:
    spec:
      chart: qbittorrent
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: k8sathome/qbittorrent
      tag: v4.3.0.1
      pullPolicy: Always
    env:
      TZ: "America/New_York"
    service:
      additionalServices:
      - enabled: true
        nameSuffix: bittorrent
        type: LoadBalancer
        port:
          port: 50413
          name: bittorrent
          protocol: TCP
          targetPort: 6881
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: https://auth.zro.io/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://auth.zro.io/oauth2/auth
      hosts:
      - host: torrent.zro.io
        paths:
        - path: /
          pathType: Prefix
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
    additionalVolumeMounts:
    - name: media
      mountPath: /media
    additionalVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: media-pool
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 1500Mi
