apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 8.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: k8sathome/radarr
      tag: v3.0.1.4259
    env:
      TZ: "America/Chicago"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: https://auth.zro.io/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://auth.zro.io/oauth2/auth
      hosts:
      - host: radarr.zro.io
        paths:
        - path: /
          pathType: Prefix
      additionalIngresses:
      - enabled: true
        nameSuffix: "api"
        hosts:
        - host: radarr.zro.io
          paths:
          - path: /api
            pathType: Prefix
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
    additionalVolumeMounts:
    - name: media
      mountPath: /media
    additionalVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: pool-media
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 1500Mi
