apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vouch
spec:
  interval: 1h
  chart:
    spec:
      chart: vouch
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: halkeye
        namespace: flux-system
  values:
    replicaCount: 2
    ingress:
      enabled: true
      hosts:
      - vouch.zro.io
    config:
      vouch:
        allowAllUsers: true
        cookie:
          domain: zro.io
        oauth:
          provider: github
          auth_url: https://git.zro.io/login/oauth/authorize
          token_url: https://git.zro.io/login/oauth/access_token
          user_info_url: https://git.zro.io/api/v1/user?token=
          callback_url: https://vouch.zro.io/auth
  valuesFrom:
  - kind: Secret
    name: credentials
    valuesKey: jwtSecret
    targetPath: config.jwt.secret
  - kind: Secret
    name: credentials
    valuesKey: clientId
    targetPath: config.oauth.client_id
  - kind: Secret
    name: credentials
    valuesKey: clientSecret
    targetPath: config.oauth.client_secret
