apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neolink-values
  namespace: neolink
spec:
  encryptedData:
    values.yaml: AgBJyoWoNRkXSq2NRS2U6dYNR8C/mb/V+mjo3FTIIufEtbdrg4xL8clo3/Bule2PRrvjnTSz7omTW6MJ09Z3ChXlNNJ9tVuiAUxYn7J67sRz8UdsqKFZANNjrcuqr62wahTk4HAmDRfVxesImlqd/2xB24ri0D5D6MRvvx7U83wAF3GUN6MKDxKxlbrXqQ8z/3uW3myvM3euUNbSUPQTiCR8bP6Q7vYaqqb2sPyQ1ww1YbqlSpJxQzZjPHprgdhJHbp8fZG1BE/8tIZRziPs3nfW+29MEMweCE1GlBuDH7Fkro70w7OpQoSH1KZlgKSViyjKGTwCSag7+Jty/PKTo0VetsaXrSwFe2MAszw1B5YE2P720nI4VA+IQ3zI/a1ma6n0vCxw4qdBmipMQ6vX47NQ1Ms6qa/oqQNkEMA51lkrq1Z34oiL6Iba9dLePEfkjpDvOC9FOSdXHh3gaNCv7QW3WvpWndku7muW9wcVyEKi91iG25uC7HEerZQh1LHiI/gjJt11paW6oLH2xB4sOs3Wh3OBvDeiMZvyIOYdV+TPfHHOtwBOjRjMt7Zi3YqY/5a3mDkrhHOE4aSx8/FQa3TSjqgb/6VJh9XIMZCu1wR0AcSOn86nGpqazCi64ugWNOYTt1I01O1RH0XLSmgUBvvZ2jMPzUJZHQWTnTCSh5sd0z2+DFM9nUmVPmDmzoLJK9J7APkIDp01pNLwoSFwLZ9nGr/QbKdKRLeOhmq0ZFwErQBVBOA9+lLza4ns/YcQRpyZ1GPLdFcdFQjly+LuMOzgAzoK0/wfLSFNd7f/NytPCT1ReU+pMoO7RxKe6jIIGcKO3ea8GzvgN1L008YiYQW7qONthk24XW7NNMmpzHrC587k5bd01LsCgfZXwaunch0Y65WOuFCUWtDHxk10Xq+VwWE=
