apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neolink-values
  namespace: neolink
spec:
  encryptedData:
    values.yaml: AgC3kguPEKMOiYKjdqk1UCkfGDL99uCFSLbbIvZ3Qs0b0IdcZmPZ0CjZx8dTvLPczPsDJtSU8CKo+k+9/+klwX+II4ohOLroVtZajCD2KG10PNCSI7ERwK4415TbsR6XqTjlxiU5ml3Jnv8xhaay6edWS0Lxk+IlwocMMY/mxAl5WwXT4qVt/+HyA413TCzWk8ze8oUtauGotd8IbahND91OA0LdWHYE8BkFE1J2mgkXvSR0MwdFsa3+94iop6LFr//UQM8EfuvuUF5656ozNgr3VKtq0nMQNqydgf8lU+NWkkKmpgwyyY+lbl7vI5wJE9BY/u+K2iVv1GpFAmTcbrKSqbJ/HM6yvW3TxOvyt5K1wEtD04SZj2J02kRt9FOe54ttT4NqdgQJxHr7q35ZKBjj5rB9G9zum7M877AR540Xqym3QKRsGdQGiG2VETuSUVYlOlKBsQJu9//eXBOlqGe6ZLKaE13Q80sVX7r4vBCj+j6LQAHY056xtQr332kBJbCeKoFzsg3I9pK/vy9NJVWACDinaeVHBSITLMoaRvwT9p8m/6qD439TAdBmjrDC0TQuVc3QttgRzlPya5XaRYaL4nVgq1YqlpzAjKnJvNda3JIiSQdBXYBgYW7TbCZe2yueYIRMzE5r8/GvyoTtjuWEgsVeYcgi8l2/MSsWYQziOlBGMCQvOy1ZFEyNbz6cozaEMdhwqU4+cbR0wZ0sk4HdZHzhIHQZ6dP+5cL7av4i9GkVtcHjWi4AEnRUtaNBXu5m+jW1Tog0wDe/WvphLdiaOT4KDcvmsfNimCiQ8mt3zgyYI8gdqr7bRnHL4Xs1Ug5suVAsicvREN3AjOHGFVMGsxQlUw+E2LPJRgIzlpSjELOR4RPcGeIirgNk/LVEk+EDeVVwQpAKl6LwjGHBIXrOwAQjYQ==
