apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neolink-values
  namespace: neolink
spec:
  encryptedData:
    values.yaml: AgBgRBufSsTgH4svEjLn7EO00ZI0bNJztdVjwFR9vW1sgVyxfZofVyN7y30hAe0eE3zqOgBaM9kx2hTBqRItHdiSHp6uQFLmJu8hxjfKfMNlRAIu9S69Nlp/mOuumvxAWTAO0fbAvoQUsdJmp7zuHfYZwi7kJqUSNAk/RhDixnBXT37SHUKmRZrJnvBNlvYsYoiTj1FSfM8VqMAaPqJ+6GaHZcObB5RmxUpbjc2F+pDubjiNN+xAxwSyyoRqId+glkVnY++xLtYSW3/gluljgBXRKYcU8ayVIz4Q87NEDgz0Ok17YDc1AX7yKbGlMea/r1iFGr4wnIKER3qnf97Oef2rOxq5SlFNz4CXG2tf8MplJE/IFXjhO/aZEwDIRmrqLWRLeZJfEgmHGk/t+qP40F7zTshfP+KRq1ipsKh+KkQSGHBoqzAzq+3J+vYTmARkDAz8t3EuN+vfWPeUcntJTx7los1iUS4L2IMqqyt6fgGEJ8oGeTU2IVqU+3qYdmS50F5tT6oyS+uIZhFBstZ6FKkj7E0/zPayKLPVhfTGI9YiSgE3ILRop/y92ClMRDrZar99LJdDXu4cgYGQzqrHZ8AB/vkeNwa6G2hP/Y/x2HAEp6ZPGjtBgdhnn08yvqf3VfM/IJGR1gj9dmzxhXgo0I1NeGJgQpqdiQ8BL4Gmq/+MY3QD2KB+WwNrZTl6noIiQ/q2iJSDq0kJELFsMmmUdWzXnNiC0NpO1EMaFN2kRFT5CT5VA2jG5lcai9LyfjNFLwPhgrc8U9z+FaPDwv4MUzm7/wuFctXnbEBdH0LfJz+l1dyI079j4cTtZStTOI6rmG2X/PB/ZAVUgAKVPiw5NFdV2NwmylaAorD5ihMI38choYPW8edgA7ZqfnfmKJBilNY=
