apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: statping
spec:
  interval: 1h
  chart:
    spec:
      chart: statping
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    statping:
      name: "Zro Ping"
    ingress:
      enabled: true
      hosts:
      - host: ping.zro.io
        paths: [ / ]
    persistence:
      enabled: true
      size: 4Gi
    postgres:
      postgresql:
        enabled: false
      kubedb:
        enabled: true
  valuesFrom:
  - kind: Secret
    name: statping-values
