apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: statping
spec:
  interval: 1h
  chart:
    spec:
      chart: statping
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      tag: v0.90.71
    statping:
      name: "Ping"
      admin:
        existingSecret:
          enabled: true
          name: credentials
          userKey: user
          passwordKey: password
          emailKey: email
    ingress:
      enabled: true
      hosts:
      - host: ping.zro.io
        paths: [ / ]
    persistence:
      enabled: true
      size: 4Gi
    env:
    - name: DB_CONN
      value: postgres
    - name: DB_HOST
      value: postgres
    - name: DB_DATABASE
      value: postgres
    - name: DB_USER
      value: postgres
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: postgres-auth
          key: password
    postgres:
      # 1.0.1 chart has this misspelled in dependencies
      posgresql:
        enabled: false
      kubedb:
        enabled: false
