---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images
  namespace: wallabag
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 8Gi

  storageClassName: rook-ceph-block
