apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiki
resources:
- namespace.yaml
- git-repo.yaml
- release.yaml
- postgres-auth.yaml
- ../../../shared/postgres

patchesStrategicMerge:
- postgres.yaml
