# extends shared/postgres.yaml
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: postgres
spec:
  authSecret:
    name: postgres-auth
  storage:
    resources:
      requests:
        storage: 50Gi
