apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wallabag
resources:
- namespace.yaml
- release.yaml
- ../../../shared/postgres
- ../../../shared/redis

# patchesStrategicMerge:
# - postgres.yaml
