---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitwarden.yaml
- blocky.yaml
- dashboard.yaml
- drone.yaml
- drone-build.yaml
- drone-secrets.yaml
- flux-system.yaml
- gitea.yaml
- home-assistant.yaml
- ingress-system.yaml
- kube-system.yaml
- kubedb-system.yaml
- longhorn-system.yaml
- media.yaml
- minio.yaml
- neolink.yaml
- nextcloud.yaml
- oauth2-proxy.yaml
- prometheus-system.yaml
- registry.yaml
- sonarqube.yaml
- unifi.yaml
- wallabag.yaml
