---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home-assistant
  name: pool-media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Ti
