---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: pool-nvr
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Ti
